<!DOCTYPE html>
<html>
	<head>
		<title> CEL </title>
		<link rel="stylesheet" type="text/css" href="style.css">
		</head>
		<?php
include('session.php');
ini_set('display_errors',0);
$db = db_open();
$code = $_GET['id'];
$result = mysql_query("SELECT * FROM emp WHERE code = '$code'" , $db);
$row = mysql_fetch_assoc($result);   
?>

		<body>
			<img src = "imgs/logo.png">
				<h3 style= "font-family : 'Arial'; font-size : 38px; align : center;margin-top : -20px"> Central Electronics Limited </h3>
				<h2 style = "position: absolute; top: 0; right: 0; font-size : 20px; margin-right: 15px; margin-top : 20px;">
					<a href = "logout.php" >Sign Out</a>
				</h2>
				<h1 style= "font-family : 'book antique'; font-size : 25px; align : center; margin-top : -15px;"> ONLINE FILE TRACKING SYSTEM </h1>
				<h1 style= "font-family : 'book antique'; font-size : 25px; align : center; margin-top : 25px;"> Send Dak </h1>
				<center>
					<button style= "font-family : 'book antique'; font-size : 18px; align : center; margin-top : 2px;" onclick="history.go(-1);">Back </button>
					<?php
{
	
	$code = $_GET['id'];
	$doc_id = $_GET['doc_id'];
	$fetch4 = mysql_query("Select * from track Where Doc_id = '$doc_id' ",$db);
	$row4 = mysql_fetch_assoc($fetch4);
	$i = 0;
	if($row4 != null)
	{
		echo	"<h2 style = 'margin-top = 50px'>Present Location Of Dak :</h2>";
		$fetch4 = mysql_query("Select * from track2 where Doc_id='$doc_id' order by S_no desc LIMIT 1",$db);
		$row3 = mysql_fetch_assoc($fetch4);
		$ids = $row3['Dispatched_To'];
		$femp = mysql_query("Select * from emp where code = '$ids'",$db);
		$row5 = mysql_fetch_assoc($femp);

		if($row5)
		{
			echo "<div>";
			$arr2 = array("ID" , "Department" , "Designation" , "Section" , "Person Concerned" );
			echo "<table rules='ALL' border = 1 style ='margin-top : 30px; '>";
			foreach($arr2 as $item)
			echo "<th  style='min-width:100px;'>".$item."</th>";
			echo "<tr>";
			foreach($row5 as $key=>$row)
			{
				if($key!="password")
				echo "<td align='center' style='min-width:100px; height : 30px'>". $row ."</td>";
			}
			echo "</table>";
			echo "</div>";
		}
		
		
		
		
		echo	"<h2>"."Details of Dak :"."</h2>";
		$ar = array("Document Number" , "Document ID" , "Description" , "Number of Pages" , "Generated By" , "Type" , "Department" , "Section" , "File Number" , "Date of Generation", "Stage" , "Action Taken" );
		echo "<table rules='ALL' border = 1  >";
		foreach($row4 as $key=>$row)
		{	if($row == "")
			$row = "------";
			echo "<tr>"."<th align='left' style='min-width:200px; height : 30px'>".$ar[$i]."</th>";
			echo "<td align='left' style='min-width:200px; height : 30px'>". $row ."</td>";
			echo "</tr>";
			echo "</td>";
			$i++;
		}
		
		$fetch = mysql_query("Select * from track2 where Doc_id='$doc_id' order by S_no desc",$db);
		$row1 = mysql_fetch_assoc($fetch);
		if($row1)
		{
			echo "<div>";
			$arr = array( "Number of Pages" , "Dispatched By" , "Person concerned" , "Dispatched To" , "Date" , "Status", "Type of dispatch" , "Remarks");
			echo "<table rules='ALL' border = 1 style ='margin-top : 30px; '>";
			foreach($arr as $item)
			echo "<th>".$item."</th>";
			while($row1)
			{
				echo "<tr>";
				foreach($row1 as $key=>$row)
				{
					if($row == "")
					$row = "------";
					if($key!="S_no" && $key!= "Doc_No" && $key!= "Doc_id" )
					echo "<td align='center' style='min-width:100px; height : 30px'>". $row ."</td>";
					$doc_id = $row1["Doc_id"];
				}
				$row1 = mysql_fetch_assoc($fetch);
			}
			echo "</table>";
			echo "</div>";
		}
		$get = mysql_query("Select * from ref where Ref_no = '$doc_id'",$db);
		$refs = mysql_fetch_assoc($get);
		while ($refs)
		{	
			$i=0;
			echo	"<h2 style = 'margin-top = 50px'>Details of Dak generated in Reference</h2>";
			$doc_id = $refs['Doc_id'];
			echo	"<h2 style = 'margin-top = 50px'>Present Location Of Dak :</h2>";
			$fetch5 = mysql_query("Select * from track2 where Doc_id='$doc_id' order by S_no desc LIMIT 1",$db);
			$row4 = mysql_fetch_assoc($fetch4);
			$ids2 = $row3['Dispatched_To'];
			$femp = mysql_query("Select * from emp where code = '$ids2'",$db);
			$row6 = mysql_fetch_assoc($femp);

			if($row6)
			{
				echo "<div>";
				$arr3 = array("ID" , "Department" , "Designation" , "Section" , "Person Concerned" );
				echo "<table rules='ALL' border = 1 style ='margin-top : 30px; '>";
				foreach($arr3 as $item)
				echo "<th style='min-width:100px;'>".$item."</th>";
				echo "<tr>";
				foreach($row6 as $key=>$row)
				{
					if($key!="password")
					echo "<td align='center' style='min-width:100px; height : 30px'>". $row ."</td>";
				}
				echo "</table>";
				echo "</div>";
			}
			
			$fetch6 = mysql_query("Select * from track Where Doc_id = '$doc_id' ",$db);
			$row6 = mysql_fetch_assoc($fetch6);
			
			echo	"<h2>"."Details of Dak :"."</h2>";
			$ar2 = array("Document Number" , "Document ID" , "Description" , "Number of Pages" , "Generated By" , "Type" , "Department" , "Section" , "File Number" , "Date of Generation", "Stage" , "Action Taken" );
			echo "<table rules='ALL' border = 1  >";
			foreach($row6 as $key=>$row)
			{	
				if($row == "")
				$row = "------";
				echo "<tr>"."<th align='left' style='min-width:200px; height : 30px'>".$ar2[$i]."</th>";
				echo "<td align='left' style='min-width:200px; height : 30px'>". $row ."</td>";
				echo "</tr>";
				echo "</td>";
				$i++;
			}
			
			$fetch = mysql_query("Select * from track2 where Doc_id='$doc_id' order by S_no desc",$db);
			$row1 = mysql_fetch_assoc($fetch);
			if($row1)
			{
				echo "<div>";
				$arr = array( "Number of Pages" , "Dispatched By" , "Person concerned" , "Dispatched To" , "Date" , "Status", "Type of dispatch" , "Remarks");
				echo "<table rules='ALL' border = 1 style ='margin-top : 30px;'>";
				foreach($arr as $item)
				echo "<th>".$item."</th>";
				while($row1)
				{
					echo "<tr>";
					foreach($row1 as $key=>$row)
					{	
						if($row == "")
						$row = "------";
						if($key!="S_no" && $key!= "Doc_No" && $key!= "Doc_id" )
						echo "<td align='center' style='min-width:100px; height : 30px'>". $row ."</td>";
						$doc_id = $row1["Doc_id"];
					}
					$row1 = mysql_fetch_assoc($fetch);
				}
				echo "</table>";
				echo "</div>";
			}
			$refs = mysql_fetch_assoc($get);
		}
	}
	else
	echo	"<h2>"."Dak not found"."</h2>";	

}
echo "<button style = 'margin-top : 20px;' onclick='history.go(-1)'>Back </button>";

?>

				</center>
			</body>
		</html>